name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: circleci/ruby:2.6-browsers

    strategy:
      matrix:
        redmine: ['4.0.4', '3.4.11']

    env:
      REDMINE: ${{ matrix.redmine }}
      RAILS_ENV: test

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Prepare Redmine
      run: |
        curl -L https://github.com/redmine/redmine/archive/${REDMINE}.tar.gz | tar xz -C /tmp
        mv /tmp/redmine-${REDMINE} /tmp/redmine
        cd /tmp/redmine

        cat <<YAML > ./config/database.yml
        test:
          adapter: sqlite3
          database: /tmp/redmine_test.sqlite3
        YAML

        # http://www.redmine.org/issues/32223
        cat <<RUBY > Gemfile.local
          gem 'sprockets', '~> 3.7.2'
        RUBY

        ln -s $GITHUB_WORKSPACE ./plugins
    - run: bundle install
      working-directory: /tmp/redmine
    - run: bin/rake db:create db:migrate
      working-directory: /tmp/redmine
    - run: bin/rake redmine:plugins:test:ui
      working-directory: /tmp/redmine
